package io.github.tomtom2211.tomsaddons.modconfig;


import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import com.terraformersmc.modmenu.api.ModMenuApi;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.text.Text;

import java.awt.*;

public class ModMenuImpl implements ModMenuApi {
    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        return parentScreen -> YetAnotherConfigLib.createBuilder()
                .title(Text.of("Tom's addons"))
                .save(() -> Config.HANDLER.save())

                // General

                .category(ConfigCategory.createBuilder()
                        .name(Text.of("General"))
                        .tooltip(Text.of("Useful stuff for skyblock."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.of("Shuriken Mob ESP"))
                                .description(OptionDescription.of(Text.of("Highlights mobs hit with extremely real shuriken.")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Toggle"))
                                        .description(OptionDescription.of(Text.of("Toggles shuriken mob ESP")))
                                        .binding(false, () -> Config.shurikenMobESP, newVal -> Config.shurikenMobESP = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Text.of("Scale"))
                                        .description(OptionDescription.of(Text.of("Makes the ESP bigger")))
                                        .binding(1.0, () -> Config.shurikenMobESPScale, newVal -> Config.shurikenMobESPScale = newVal)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(0.1, 10.0)
                                                .step(0.1))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.of("Color"))
                                        .description(OptionDescription.of(Text.of("Sets the color of the ESP outline")))
                                        .binding(Color.cyan, () -> Config.shurikenMobESPColor, newVal -> Config.shurikenMobESPColor = newVal)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build())
                                .build())

                        .build())

                // Dungeons

                .category(ConfigCategory.createBuilder()
                        .name(Text.of("Dungeons"))
                        .tooltip(Text.of("Useful stuff for dungeons."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.of("Starred Mob ESP"))
                                .description(OptionDescription.of(Text.of("Highlights starred mobs in dungeons.")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Toggle"))
                                        .description(OptionDescription.of(Text.of("Toggles starred mob ESP")))
                                        .binding(false, () -> Config.starredMobESP, newVal -> Config.starredMobESP = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Text.of("Scale"))
                                        .description(OptionDescription.of(Text.of("Makes the ESP bigger")))
                                        .binding(1.0, () -> Config.starredMobESPScale, newVal -> Config.starredMobESPScale = newVal)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(0.1, 10.0)
                                                .step(0.1))
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.of("Color"))
                                        .description(OptionDescription.of(Text.of("Sets the color of the ESP outline")))
                                        .binding(Color.red, () -> Config.starredMobESPColor, newVal -> Config.starredMobESPColor = newVal)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.of("Immunity Timers"))
                                .description(OptionDescription.of(Text.of("Displays immunity cooldowns for phoenix, bonzo's mask, spirit mask.")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Toggle"))
                                        .description(OptionDescription.of(Text.of("Toggles Immunity Timers")))
                                        .binding(false, () -> Config.immunityTimers, newVal -> Config.immunityTimers = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Phoenix"))
                                        .description(OptionDescription.of(Text.of("Toggle phoenix timer")))
                                        .binding(true, () -> Config.phoenixPet, newVal -> Config.phoenixPet = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Bonzo's mask"))
                                        .description(OptionDescription.of(Text.of("Toggle bonzo's mask timer")))
                                        .binding(true, () -> Config.bonzoMask, newVal -> Config.bonzoMask = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Spirit mask"))
                                        .description(OptionDescription.of(Text.of("Toggle Spirit Mask Timer")))
                                        .binding(true, () -> Config.spiritMask, newVal -> Config.spiritMask = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.of("Catacombs level"))
                                        .description(OptionDescription.of(Text.of("Used for bonzo's mask cooldown reduction calculation.")))
                                        .binding(50, () -> Config.cataLVL, newVal -> Config.cataLVL = newVal)
                                        .controller(opt -> IntegerFieldControllerBuilder.create(opt)
                                                .range(0, 50))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.of("Command Aliases"))
                                .description(OptionDescription.of(Text.of("Makes aliases for /joindungeon commands (for example /m7).")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Toggle"))
                                        .description(OptionDescription.of(Text.of("Toggles Command Aliases.")))
                                        .binding(false, () -> Config.commandAliases, newVal -> Config.commandAliases = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.of("Instant requeue"))
                                .description(OptionDescription.of(Text.of("Instantly re-queues after dungeon/kuudra run ends.")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Toggle"))
                                        .description(OptionDescription.of(Text.of("Toggles Command Aliases.")))
                                        .binding(false, () -> Config.instantRequeue, newVal -> Config.instantRequeue = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())

                // Kuudra

                .category(ConfigCategory.createBuilder()
                        .name(Text.of("Kuudra"))
                        .tooltip(Text.of("Useful stuff for Kuudra."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.of("Kuudra prediction"))
                                .description(OptionDescription.of(Text.of("Predicts Kuudra Tier V last-phase peek sides.")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Toggle"))
                                        .description(OptionDescription.of(Text.of("Toggles Kuudra Prediction.")))
                                        .binding(false, () -> Config.kuudraPrediction, newVal -> Config.kuudraPrediction = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Force"))
                                        .description(OptionDescription.of(Text.of("Forces Kuudra Prediction (used for moving gui).")))
                                        .binding(false, () -> Config.forceKuudraPredictionHUD, newVal -> Config.forceKuudraPredictionHUD = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.of("Set X"))
                                        .description(OptionDescription.of(Text.of("Moves the Kuudra's Prediction HUD from the centre. ")))
                                        .binding(10, () -> Config.kuudraPredictionX, newVal -> Config.kuudraPredictionX = newVal)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.of("Set Y"))
                                        .description(OptionDescription.of(Text.of("Moves the Kuudra's Prediction HUD from the centre.")))
                                        .binding(0, () -> Config.kuudraPredictionY, newVal -> Config.kuudraPredictionY = newVal)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())

                                .option(Option.<Color>createBuilder()
                                        .name(Text.of("Color"))
                                        .description(OptionDescription.of(Text.of("Sets the color of the ESP outline")))
                                        .binding(Color.cyan, () -> Config.kuudraPreHUDColor, newVal -> Config.kuudraPreHUDColor = newVal)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build())
                                .build())
                        .build())

                // Mining

                .category(ConfigCategory.createBuilder()
                        .name(Text.of("Mining"))
                        .tooltip(Text.of("Useful stuff for Mining."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.of("Mining Timers"))
                                .description(OptionDescription.of(Text.of("Displays current cooldowns of mining abilities (pickobulus/mining speed boost).")))

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Toggle"))
                                        .description(OptionDescription.of(Text.of("Toggles Mining Timers.")))
                                        .binding(false, () -> Config.miningTimers, newVal -> Config.miningTimers = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())

                                .option(Option.<Color>createBuilder()
                                        .name(Text.of("Color"))
                                        .description(OptionDescription.of(Text.of("Sets the color of the ESP outline")))
                                        .binding(Color.green, () -> Config.miningTimersColor, newVal -> Config.miningTimersColor = newVal)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.of("Bal lvl 100"))
                                        .description(OptionDescription.of(Text.of("Toggle if you are using legendary bal pet lvl 100.")))
                                        .binding(false, () -> Config.balLvl100, newVal -> Config.balLvl100 = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())

                                .option(Option.<String>createBuilder()
                                        .name(Text.of("Drill Engine"))
                                        .description(OptionDescription.of(Text.of("Select if you are using drill engine.")))
                                        .binding("None", () -> Config.drillEngine, newVal -> Config.drillEngine = newVal)
                                        .controller(opt -> DropdownStringControllerBuilder.create(opt)
                                                .values("None", "Mithril-Infused", "Titanium-Infused", "Gemstone", "Perfectly-Cut"))
                                        .build())

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.of("Pickobulus Level"))
                                        .description(OptionDescription.of(Text.of("Set your pickobulus level.")))
                                        .binding(1, () -> Config.pickobulusLevel, newVal -> Config.pickobulusLevel = newVal)
                                        .controller(opt -> IntegerFieldControllerBuilder.create(opt)
                                                .range(1, 3))
                                        .build())


                                .build())
                        .build())
                .build()
                .generateScreen(parentScreen);
    }
}