package io.github.tomtom2211.tomsaddons.features;

import net.minecraft.client.MinecraftClient;
import net.minecraft.client.option.KeyBinding;
import java.util.Objects;
import java.util.Random;

public class Jokes {
    Random rand = new Random(); // For random numbers
    public Long buttonPressTime = System.currentTimeMillis(); // Used for delays
    MinecraftClient mcClient = MinecraftClient.getInstance(); // Minecraft client instance
    public String[] jokes = {
            "Why did the Healer bring a pickaxe to dungeons? Because it was the only way they'd ever get carried.",
            "A Healer walks into Floor 7. The party says: 'Wait, this isn’t Bedwars—why are you here?'",
            "What’s a Healer’s favorite weapon? The Party Finder 'kick' button.",
            "How do you make a Healer feel useful? Pretend you didn’t bring a Wand of Atonement.",
            "Why don’t Healers ever die? Because they’re already dead inside after 500 runs of Floor 5.",
            "What’s a Healer’s ultimate ability? Convincing the party that they actually matter.",
            "Why do Berserkers love Healers? Because someone has to revive them after they jump into a miniboss alone.",
            "How do you spot a Healer in a dungeon run? They’re the one with the lowest damage and the highest hope.",
            "What’s the hardest part about being a Healer? Explaining to your party why you’re not actually AFK.",
            "Why did the Healer quit SkyBlock? They realized their pet rock does more DPS.",
            "Why do parties only bring Healers once? To remember why they don’t bring them again.",
            "What’s a Healer’s main stat? Patience… for waiting to be replaced by a Tank.",
            "How many Healers does it take to clear Floor 7? Nobody knows, they never make it that far.",
            "Why did the Healer fail the puzzle room? They were too busy reviving themselves emotionally.",
            "What do you call a Healer with high DPS? A liar.",
            "Why do Healers love Fairy Rooms? Because finally, someone else is healing them.",
            "What’s the difference between a Healer and a Spirit Leprechaun? One drops loot, the other just drops performance.",
            "Why don’t Healers argue? They don’t have the DPS to back it up.",
            "What’s a Healer’s favorite song? 'Stayin’ Alive.'",
            "Why did the Healer refuse to fight Necron? They didn’t want to break their zero damage record.",
            "What’s the similarity between a Healer and a Treasure Talisman? Both are rare… and still useless.",
            "Why don’t Healers play Archer? Because bows do too much damage and it scares them.",
            "What’s a Healer’s secret weapon? Guilt-tripping the party into keeping them around.",
            "Why do Tanks and Healers get along? Because misery loves company.",
            "What’s a Healer’s favorite dungeon role? Spectator.",
            "Why did the Healer cross the dungeon? To rez the Berserker who thought he was immortal.",
            "What’s a Healer’s favorite miniboss? None. They’re all just more work.",
            "Why don’t Healers get lost in dungeons? Because everyone leaves them behind anyway.",
            "What’s the difference between a Healer and a potion? At least the potion is useful.",
            "Why did the Healer bring a Flower of Truth? To convince themselves they’re helpful.",
            "What do Healers call 1 million damage? A group effort.",
            "Why are Healers like puzzle rooms? Everyone groans when they see one.",
            "Why did the Healer stop attacking? They didn’t want to risk stealing aggro.",
            "What’s the Healer’s motto? 'I revive, therefore I am… tolerated.'",
            "Why do parties only invite Healers at low levels? To teach them disappointment early.",
            "What’s the scariest word for a Healer? 'Solo run.'",
            "Why did the Healer sit in the corner? Because their damage was already grounded.",
            "What’s a Healer’s favorite boss phase? The one where everyone else does the work.",
            "Why don’t Healers ever get blamed? Because nobody remembers they exist.",
            "What do you call a Healer with a Terminator? A very confused Archer.",
            "Why do Healers love spirit pets? Because they’re used to being ghosts.",
            "What’s a Healer’s best dungeon strategy? Hiding behind the Tank.",
            "Why did the Healer bring 10 stacks of healing pots? Habit.",
            "What’s the Healer’s biggest fear? Someone finding out they’re replaceable.",
            "Why do Healers like revive stones? They finally get to feel needed.",
            "Why don’t Healers flex their gear? Because no one’s impressed by mender crowns.",
            "What’s a Healer’s spirit animal? A fairy—it dies constantly, but keeps coming back.",
            "Why do Healers make good friends? Because they’re used to supporting people better than them.",
            "What’s the Healer’s dungeon carry method? Emotional support.",
            "Why do Healers love Catacombs? Because it’s the only place they feel like they belong—barely.",
            "Why did the Healer start the run late? They were busy crafting excuses.",
            "What’s a Healer’s dream weapon? Anything that does more than 10k damage.",
            "Why don’t Healers need backpacks? They carry no weight in the team.",
            "What do you call a Healer with full Necron armor? Lost.",
            "Why do parties bring Healers to Floor 7? For moral support, not actual support.",
            "What’s a Healer’s least favorite sound? 'We don’t need one.'",
            "Why did the Healer buy Storm armor? To cosplay as someone useful.",
            "What’s the best upgrade for a Healer? /party leave.",
            "Why do Healers always smile? To hide the pain of being irrelevant.",
            "What’s a Healer’s favorite floor? Entrance, because it’s the only one they survive.",
            "Why did the Healer open a dungeon chest? To see disappointment in HD.",
            "What’s the difference between a Healer and a spirit leap? The leap is faster.",
            "Why don’t Healers invest in talismans? No amount of reforges can fix uselessness.",
            "What’s a Healer’s favorite armor piece? Mender crown, because it screams 'I gave up'.",
            "Why did the Healer run Tank? To finally be noticed.",
            "What do Healers and treasure chests have in common? Both are ignored until needed.",
            "Why did the Healer buy a Juju? Midlife crisis.",
            "What’s a Healer’s biggest achievement? Getting carried without being kicked.",
            "Why do Tanks secretly like Healers? Because someone has to look weaker than them.",
            "What’s a Healer’s best dungeon role? Lobby decoration.",
            "Why don’t Healers duel people? They’d lose to Hub villagers.",
            "What’s a Healer’s main dungeon drop? Regret.",
            "Why did the Healer’s team disband? They realized fairy rooms already exist.",
            "What’s the difference between a Healer and lag? At least lag has an effect.",
            "Why do Healers never win arguments? Because 'you did 0 damage' ends it instantly.",
            "What’s a Healer’s spirit guide? The fairy in dungeons, because they share a grave.",
            "Why did the Healer buy recombs? To feel valuable at least once.",
            "What’s a Healer’s training routine? Practicing /revive.",
            "Why don’t Healers get SkyBlock levels? They don’t contribute to anything.",
            "What’s the Healer’s favorite activity? AFKing, just like in dungeons.",
            "Why do Healers struggle in boss fights? Because they’re allergic to relevance.",
            "What’s the most dangerous thing a Healer can do? Try to deal damage.",
            "Why did the Healer wear Wither goggles? To pretend they’re a mage.",
            "What’s a Healer’s favorite minigame? Hide and seek—already mastered in dungeons.",
            "Why do Healers always type 'ez'? Because it’s the only short thing they can handle.",
            "What’s the similarity between a Healer and cobblestone? Both are abundant and ignored.",
            "Why did the Healer grind Catacombs XP? To hit milestones no one asked for.",
            "What’s a Healer’s hidden talent? Dying quietly.",
            "Why don’t parties argue with Healers? They just kick them instead.",
            "What’s the Healer’s favorite cosmetic? Anything that hides them.",
            "Why did the Healer fail trap room? They thought it was a damage test.",
            "What do you call a Healer in Shadow Assassin armor? A disappointment in black.",
            "Why do Healers love dungeon blessings? Because they’re the only thing boosting them.",
            "What’s a Healer’s favorite boss? Bonzo—because at least he’s a clown too.",
            "Why don’t Healers use hype? They’d heal less with it.",
            "What’s a Healer’s dungeon contribution? Being a revive checkpoint.",
            "Why did the Healer invest in fishing gear? Same role, more profit.",
            "What’s a Healer’s best party finder note? 'pls don’t kick'.",
            "Why do Healers fear Mages? Because they do the same job, but actually useful.",
            "What’s a Healer’s farewell message? 'You guys didn’t need me anyway.'"
    };
    public void jokeLogic(KeyBinding joke){
        if(joke.wasPressed() && System.currentTimeMillis()-buttonPressTime>=1000) {
            int randomNum = rand.nextInt(100);
            Objects.requireNonNull(mcClient.getNetworkHandler()).sendChatMessage(jokes[randomNum]);
            buttonPressTime = System.currentTimeMillis();
        }
    }
}
